# hash:sha256:bd4e56884f964ec80a8ff04e67ed508312af83f2fff9d9e61afac58ef4084e42
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/mosuite-minimal:v0.5.0-alpha

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-ask-pass /
